services:
  api:
    container_name: api
    build:
      context: ./app/.
      dockerfile: Dockerfile
    command: fastapi run
    volumes:
      - ./db:/app/db
      - ./media:/app/media
    networks:
      - project_network
    ports:
      - 8000:8000

  server:
    container_name: nginx
    build:
      context: ./server-nginx/.
      dockerfile: Dockerfile
    volumes:
      - ./media:/usr/share/nginx/html/media
    depends_on:
      - api
    networks:
      - project_network
    ports:
      - 8080:8080

networks:
  project_network:
    driver: bridge